// <auto-generated />
using System;
using ManageGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageGames.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804160242_PasswordRequired")]
    partial class PasswordRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ManageGames.Models.CompanyModel", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CompanyName");

                    b.HasKey("CompanyId");

                    b.ToTable("tblCompanies", (string)null);
                });

            modelBuilder.Entity("ManageGames.Models.ConsoleModel", b =>
                {
                    b.Property<int>("ConsoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Company");

                    b.Property<string>("ConsoleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ConsoleName");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ConsoleId");

                    b.HasIndex("CompanyId");

                    b.ToTable("tblConsoles", (string)null);
                });

            modelBuilder.Entity("ManageGames.Models.GameModel", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<int>("ConsoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Console");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Copies");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GameName");

                    b.Property<bool>("IsOnWishList")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsOnWishList");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserID");

                    b.HasKey("GameId");

                    b.HasIndex("ConsoleId");

                    b.HasIndex("UserId");

                    b.ToTable("tblGames", (string)null);
                });

            modelBuilder.Entity("ManageGames.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("TEXT")
                        .HasColumnName("UserID");

                    b.Property<string>("CookieID")
                        .HasColumnType("TEXT")
                        .HasColumnName("CookieID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsAdmin");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NormalizedUsername");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<Guid>("ProfilePicturesID")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProfilePicturesID");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Username");

                    b.HasKey("UserID");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("tblUser", (string)null);
                });

            modelBuilder.Entity("ManageGames.Models.ConsoleModel", b =>
                {
                    b.HasOne("ManageGames.Models.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ManageGames.Models.GameModel", b =>
                {
                    b.HasOne("ManageGames.Models.ConsoleModel", "Console")
                        .WithMany()
                        .HasForeignKey("ConsoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManageGames.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Console");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
